FROM golang:1.19-alpine

WORKDIR /go/src/target
COPY go.mod ./
COPY go.sum ./
RUN go mod tidy
RUN go mod download
COPY . ./
RUN go build -o /docker-go


ENV DATABASE_URL postgres://mwabtxlk:x4mWGDcSX0VqkVEugDsAkXesZOAazEwF@tiny.db.elephantsql.com/mwabtxlk
ENV PORT :2565
EXPOSE 2565
CMD ["/docker-go"]