FROM golang:1.19-alpine

# Set working directory
WORKDIR /go/src/target
COPY go.mod ./
COPY go.sum ./
RUN go mod tidy
RUN go mod download
COPY . ./

# # Run tests

RUN CGO_ENABLED=0  go test --tags=integration -c -o /foo
CMD ["/foo"]